on:
  schedule:
    - cron:  '* */2 * * *'
    # scheduled to run in each 2-hour interval
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master
        
    - name: Pull upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.2
      with:
        upstream_repository: apache/arrow
        upstream_branch: master
        target_branch: master

    - name: Timestamp
      run: date
